name: Automatic Release on Dependabot Pull Request
on:
  pull_request:
    branches: [ master ]

jobs:
  merge-pr_and_release:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Merge Pull Request
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Check source changes
        run: |
          if [[ -z "$(git diff-tree --no-commit-id --name-only -m -r HEAD -- plugin/)" ]];
          then
            echo "::set-env name=detect_source_change::0"
          else
            echo "::set-env name=detect_source_change::1"
          fi

      - name: Fetch Dependencies (if detect source changed)
        if: env.detect_source_change == '1'
        run: npm install

      - name: Build (if detect source changed)
        if: env.detect_source_change == '1'
        run: npm run build --if-present

      - name: Bump Version
        run: npm --no-git-tag-version version patch

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Release new version for automatic PR merging.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
